#!/bin/bash

set -euo pipefail

DOCKER_REPO=tessereth/test-summary-buildkite-plugin

# cd to plugin directory
cd "$( dirname "${BASH_SOURCE[0]}" )/.."
TAG=$(git describe --tags --exact-match 2> /dev/null || true)

if [[ -n "$TAG" ]]; then
    echo "Found tag $TAG, pulling from docker hub"
    IMAGE="$DOCKER_REPO:$TAG"
    docker pull "$IMAGE"
else
    echo "No tag found, building image locally"
    IMAGE=test-summary:$BUILDKITE_JOB_ID
    docker build -t "$IMAGE" .
fi

docker run --rm \
  --mount type=bind,src=$(which buildkite-agent),dst=/usr/bin/buildkite-agent \
  -e BUILDKITE_BUILD_ID -e BUILDKITE_JOB_ID -e BUILDKITE_AGENT_ACCESS_TOKEN -e BUILDKITE_PLUGINS \
  $IMAGE
